# Config Client
spring:
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: local

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}-LOCAL
    status-page-url: http://localhost:${server.port}/swagger-ui/index.html
